apiVersion: v1
kind: pod
metadata:
  name: env-demo
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: ENVIRONMENT
          value: "production"
        - name: course
          value: "kubernetes for beginners"